name: "frontend"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`goida.dev`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: "traefik-network"
    external: true